### ISSUE TITLE
ReviewError: More than one srpm found

### ISSUE THREAD

**Issue by abompard** [FrostyX/fedora-review-service#47]
I'm getting this error on a package that uses the [forge macros](https://docs.fedoraproject.org/en-US/packaging-guidelines/SourceURL/#_using_forges_hosted_revision_control):

```
ReviewError: 'More than one srpm found for: /var/lib/copr-rpmbuild/results/kfreestyle2d*.src.rpm'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/FedoraReview/review_helper.py", line 236, in run
    self._do_run(outfile)
  File "/usr/lib/python3.12/site-packages/FedoraReview/review_helper.py", line 226, in _do_run
    self._do_report(outfile)
  File "/usr/lib/python3.12/site-packages/FedoraReview/review_helper.py", line 83, in _do_report
    if not self.bug.find_urls():
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/FedoraReview/abstract_bug.py", line 202, in find_urls
    raise fre
  File "/usr/lib/python3.12/site-packages/FedoraReview/abstract_bug.py", line 194, in find_urls
    self.find_srpm_url()
  File "/usr/lib/python3.12/site-packages/FedoraReview/name_bug.py", line 58, in find_srpm_url
    raise self.BugError("More than one srpm found for: " + pattern)
FedoraReview.abstract_bug.AbstractBug.BugError: 'More than one srpm found for: /var/lib/copr-rpmbuild/results/kfreestyle2d*.src.rpm'
```

It's at https://download.copr.fedorainfracloud.org/results/@fedora-review/fedora-review-2279495-kfreestyle2d/fedora-rawhide-x86_64/07435494-kfreestyle2d/fedora-review/fedora-review.log.gz

The corresponding BZ ticket is https://bugzilla.redhat.com/show_bug.cgi?id=2279495

**Comment by FrostyX** [comment]
Thank you for the report @abompard.
There is nothing that Fedora Review Service can do about this. The traceback comes from the `fedora-review` tool, so we should file the issue to its tracker
https://pagure.io/FedoraReview/issues

I will do it later today.

**Comment by FrostyX** [comment]
I reported a `fedora-review` issue 
https://pagure.io/FedoraReview/issue/519 
and closing this ticket because there is nothing we can do about it here.
